version: "3"

services:
  web:
    build: .
    image: automatizacion-decode:1.0
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html/
 
#volumes:
#  decode-automatizacion:
#    driver: local